"""A DEMO-only copy of config/ for running the full approve -> post loop.

``write_demo_config`` copies every config/*.yaml into a throwaway directory
(default data/demo-config/, gitignored) and, in that copy only:

- marks every claim ``approved_by: "DEMO (not signed off)"`` (approved today),
  so the approval gate's publishable-claims check passes in demos;
- sets every registry link ``live: true``;
- registers the fictional sandbox forum communities in communities.yaml
  (``demo: true``) with a spread of rules, so a demo shows every branch of the
  rules of engagement: allowed (with and without links), admin permission not
  yet obtained, brand replies prohibited (no reply; the protocol's DO NOT
  ENGAGE), and one left unregistered (rules unverified; the protocol HOLDs);
- gives every FINALIZE item that blocks approval a DEMO placeholder value, so
  Template C complaint replies can run the approve -> post loop (claims with
  an unfilled [slot] stay blocked: only a human can fill those);
- writes the marker file ``demo.yaml`` (``demo_config: true``), which makes the
  dashboard show a persistent "DEMO CONFIG" banner (``knowledge.is_demo_config``).

The real config/ is never touched. Point ``PULSE_CONFIG_DIR`` at the copy
only for demos.
"""

import shutil
from datetime import date
from pathlib import Path

import yaml

from harvey.paths import PROJECT_ROOT

DEMO_APPROVER = "DEMO (not signed off)"
MARKER_FILE = "demo.yaml"
MARKER_KEY = "demo_config"
DEFAULT_DIR = PROJECT_ROOT / "data" / "demo-config"
DEMO_FINALIZE_VALUE = "DEMO placeholder - not established by WellPeps"
# Fictional sandbox forum communities (harvey/sandbox/demo_content.py) and the
# rules the DEMO copy gives them. "quick_takes" is left out on purpose: its
# rules stay unverified.
DEMO_COMMUNITIES = (
    ("tirzepatide_talk", "allowed", False, False),
    ("glp1_journey", "allowed", True, False),
    ("telehealth_reviews", "allowed", True, False),
    ("hairloss_help", "allowed", True, False),
    ("menshealth_q", "allowed", False, False),
    ("peptide_questions", "with_permission", False, False),
    ("glp1_support_group", "prohibited", False, False),
)
HEADER = ("# DEMO CONFIG: generated by scripts/seed_demo.py --sandbox. Claims are marked approved for\n"
          "# demonstration only (NOT signed off) and every link is marked live. Never use for real replies.\n")


def write_demo_config(target: str | Path = DEFAULT_DIR, source: str | Path | None = None,
                      today: date | None = None) -> Path:
    target = Path(target)
    source = Path(source) if source else PROJECT_ROOT / "config"
    if target.resolve() == (PROJECT_ROOT / "config").resolve() or target.resolve() == source.resolve():
        raise ValueError("refusing to overwrite the real config directory with a DEMO config")
    day = (today or date.today()).isoformat()
    target.mkdir(parents=True, exist_ok=True)
    for path in sorted(source.glob("*.yaml")):
        shutil.copyfile(path, target / path.name)

    claims = yaml.safe_load((target / "claims.yaml").read_text(encoding="utf-8")) or {}
    for claim in claims.get("claims", []):
        claim.update(approved_by=DEMO_APPROVER, approved_at=day, expires=None)
    _dump(target / "claims.yaml", claims)

    links = yaml.safe_load((target / "links.yaml").read_text(encoding="utf-8")) or {}
    for link in links.get("links", []):
        link.update(live=True, checked_at=day)
    _dump(target / "links.yaml", links)

    communities = yaml.safe_load((target / "communities.yaml").read_text(encoding="utf-8")) or {}
    entries = [c for c in communities.get("communities") or [] if not c.get("demo")]
    for name, participation, links_allowed, permission in DEMO_COMMUNITIES:
        entries.append({"id": f"sandbox:c/{name}", "platform": "sandbox", "name": f"c/{name}",
                        "brand_participation": participation, "links_allowed": links_allowed,
                        "permission_obtained": permission, "moderator_contact": "",
                        "rules_checked_at": day, "notes": "DEMO community (fictional sandbox forum)",
                        "demo": True})
    communities["communities"] = entries
    _dump(target / "communities.yaml", communities)

    guide = yaml.safe_load((target / "engagement_guide.yaml").read_text(encoding="utf-8")) or {}
    for item in guide.get("finalize") or []:
        if item.get("blocks_approval") and not item.get("value"):
            item["value"] = DEMO_FINALIZE_VALUE
    _dump(target / "engagement_guide.yaml", guide)

    _dump(target / MARKER_FILE, {MARKER_KEY: True, "note": "DEMO CONFIG - claims marked approved for "
                                 "demonstration only; never use for real replies."})
    return target


def _dump(path: Path, data: dict) -> None:
    path.write_text(HEADER + yaml.safe_dump(data, sort_keys=False, allow_unicode=True), encoding="utf-8")


def is_demo_config(directory: str | Path) -> bool:
    marker = Path(directory) / MARKER_FILE
    if not marker.is_file():
        return False
    try:
        data = yaml.safe_load(marker.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError):
        return False
    return isinstance(data, dict) and data.get(MARKER_KEY) is True
