-- ============================================================================
-- WellPeps Pulse: Postgres (Supabase) schema, equivalent to SQLite v1..v5
-- (harvey/state.py MIGRATIONS). Apply once; safe to re-run (idempotent).
--
-- Conventions (see db/postgres/README.md):
-- * Timestamps are `timestamp without time zone` holding naive UTC, exactly
--   the values the SQLite build stores. Defaults use now() AT TIME ZONE 'utc'.
-- * *_json columns stay `text` holding JSON: the app encodes/decodes them
--   itself, so jsonb would only add behaviour drift (key order, spacing).
-- * SQLite 0/1 flags are `boolean`. INTEGER PRIMARY KEY AUTOINCREMENT is
--   `bigint generated by default as identity`; text ids stay text.
-- * Every table has row level security ON. anon/authenticated get no grants
--   and no policies; the schema is not in Supabase's exposed API schemas.
--   Only the NOLOGIN role pulse_app (plus the owner) can use it.
-- * No secrets here. Login roles/passwords are a manual step (README).
-- ============================================================================

create schema if not exists pulse;

-- Version marker the app checks at startup (StateManager.init_db).
create table if not exists pulse.schema_version (
    version integer primary key,
    description text not null default '',
    applied_at timestamp not null default (now() at time zone 'utc')
);

-- ── Operational plumbing ─────────────────────────────────────────────────

create table if not exists pulse.settings (
    key text primary key,
    value text default '',
    updated_at timestamp default (now() at time zone 'utc')
);

create table if not exists pulse.runs (
    id text primary key,
    stage text default '',
    status text default 'running',
    provider text default '',
    records integer default 0,
    cost_usd double precision default 0.0,
    params_json text default '{}',
    error text default '',
    started_at timestamp default (now() at time zone 'utc'),
    ended_at timestamp
);
create index if not exists idx_runs_stage_started on pulse.runs (stage, started_at);

create table if not exists pulse.actions (
    id text primary key,
    action_type text,
    agent text,
    details_json text default '{}',
    created_at timestamp default (now() at time zone 'utc')
);
create index if not exists idx_actions_created_at on pulse.actions (created_at);

create table if not exists pulse.usage_log (
    id text primary key,
    date text unique,
    claude_calls integer default 0,
    usage_percent double precision default 0.0,
    created_at timestamp default (now() at time zone 'utc')
);

create table if not exists pulse.usage_events (
    id text primary key,
    created_at timestamp default (now() at time zone 'utc'),
    agent text default '',
    task text default '',
    session_id text default '',
    request_key text default '',
    model text default '',
    input_tokens integer default 0,
    output_tokens integer default 0,
    cache_read_tokens integer default 0,
    cache_creation_tokens integer default 0,
    cost_usd double precision default 0.0,
    duration_ms integer default 0,
    num_turns integer default 0,
    is_error boolean default false,
    source text default 'result_json'
);
create index if not exists idx_usage_events_created on pulse.usage_events (created_at);
create index if not exists idx_usage_events_agent on pulse.usage_events (agent);
create index if not exists idx_usage_events_session on pulse.usage_events (session_id);
create unique index if not exists uq_usage_events_request
    on pulse.usage_events (request_key) where request_key <> '';

-- ── Listening ────────────────────────────────────────────────────────────

create table if not exists pulse.sources (
    id bigint generated by default as identity primary key,
    collector text not null,
    name text default '',
    config_json text default '{}',
    enabled boolean default true,
    owned boolean default false,
    last_cursor text default '',
    last_run_at timestamp,
    created_at timestamp default (now() at time zone 'utc')
);

create table if not exists pulse.mentions (
    id bigint generated by default as identity primary key,
    source_id bigint references pulse.sources (id),
    platform text not null,
    external_id text default '',
    url text not null,
    url_norm text not null,
    author_handle text default '',
    parent_external_id text default '',
    text text default '',
    title text default '',
    lang text default '',
    posted_at timestamp,
    collected_at timestamp default (now() at time zone 'utc'),
    engagement_json text default '{}',
    owned_channel boolean default false,
    status text default 'new',
    run_id text default ''
);
create unique index if not exists uq_mentions_platform_external
    on pulse.mentions (platform, external_id) where external_id <> '';
create unique index if not exists uq_mentions_url_norm on pulse.mentions (url_norm);
create index if not exists idx_mentions_status on pulse.mentions (status, collected_at);
create index if not exists idx_mentions_collected on pulse.mentions (collected_at);
create index if not exists idx_mentions_platform on pulse.mentions (platform, collected_at);
create index if not exists idx_mentions_source on pulse.mentions (source_id);

create table if not exists pulse.triage (
    mention_id bigint primary key references pulse.mentions (id),
    relevant boolean default true,
    subject_type text default '',
    subject text default '',
    competitor text default '',
    product text default '',
    category text default 'other',
    sentiment text default '',
    urgency text default 'normal',
    urgency_reason text default '',
    reply_appropriate boolean default false,
    phrases_json text default '[]',
    model text default '',
    created_at timestamp default (now() at time zone 'utc'),
    sentiment_score double precision default 0.0,   -- SQLite v2
    drug text default ''                            -- SQLite v3
);
create index if not exists idx_triage_category on pulse.triage (category);
create index if not exists idx_triage_urgency on pulse.triage (urgency);
create index if not exists idx_triage_drug on pulse.triage (drug);

create table if not exists pulse.escalations (
    id bigint generated by default as identity primary key,
    mention_id bigint not null references pulse.mentions (id),
    kind text default '',
    owner text default '',
    notified_at timestamp,
    sla_due_at timestamp,
    acked_at timestamp,
    acked_by text default '',
    breached boolean default false,
    created_at timestamp default (now() at time zone 'utc')
);
create index if not exists idx_escalations_mention on pulse.escalations (mention_id);
create index if not exists idx_escalations_open on pulse.escalations (acked_at, sla_due_at);

-- ── Drafting & review ────────────────────────────────────────────────────

create table if not exists pulse.drafts (
    id bigint generated by default as identity primary key,
    mention_id bigint not null references pulse.mentions (id),
    version integer not null,
    text text default '',
    claim_ids_json text default '[]',
    model text default '',
    filter_ok boolean,
    filter_hits_json text default '[]',
    review_verdict text,
    review_reasons_json text default '[]',
    tier text default '',
    created_at timestamp default (now() at time zone 'utc'),
    unique (mention_id, version)
);

-- Append-only record of every decision. Triggers below forbid edits.
create table if not exists pulse.audit_log (
    id bigint generated by default as identity primary key,
    mention_id bigint,
    draft_id bigint,
    event text not null,
    actor text not null default '',
    claim_ids_json text default '[]',
    filter_result_json text default '{}',
    verdict_json text default '{}',
    final_text text default '',
    permalink text default '',
    at timestamp default (now() at time zone 'utc')
);
create index if not exists idx_audit_mention on pulse.audit_log (mention_id, id);
create index if not exists idx_audit_at on pulse.audit_log (at);

create or replace function pulse.audit_log_append_only()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    raise exception 'audit_log is append-only: % not allowed', tg_op
        using errcode = 'P0001';
end;
$$;

drop trigger if exists trg_audit_log_no_update_delete on pulse.audit_log;
create trigger trg_audit_log_no_update_delete
    before update or delete on pulse.audit_log
    for each row execute function pulse.audit_log_append_only();

drop trigger if exists trg_audit_log_no_truncate on pulse.audit_log;
create trigger trg_audit_log_no_truncate
    before truncate on pulse.audit_log
    for each statement execute function pulse.audit_log_append_only();

-- ── Intelligence (SQLite v5 shape) ───────────────────────────────────────

create table if not exists pulse.briefs (
    id bigint generated by default as identity primary key,
    period text not null,                     -- daily | weekly
    window_start timestamp not null,          -- naive UTC
    window_end timestamp not null,
    status text default 'ok',                 -- ok | fallback
    headline text default '',
    summary_md text default '',
    action_cards_json text default '[]',
    watchlist_json text default '[]',
    data_json text default '{}',
    model text default '',
    slack_sent_at timestamp,
    created_at timestamp default (now() at time zone 'utc'),
    unique (period, window_start)
);

create table if not exists pulse.trend_terms (
    id bigint generated by default as identity primary key,
    brief_id bigint not null references pulse.briefs (id),
    rank integer not null,
    term text not null,
    count integer default 0,
    baseline_count integer default 0,
    velocity double precision default 0.0,
    score double precision default 0.0,
    is_new boolean default false,
    example_ids_json text default '[]',
    unique (brief_id, term)
);

create table if not exists pulse.language_bank (
    id bigint generated by default as identity primary key,
    phrase text not null,                     -- first verbatim form seen
    phrase_norm text not null,                -- lowercased, whitespace collapsed
    scope text not null default '',           -- WellPeps product, else drug, else ''
    product text default '',
    drug text default '',
    category text default '',
    sentiment text default '',
    example_mention_id bigint,
    count integer default 0,
    first_seen timestamp,
    last_seen timestamp,
    unique (phrase_norm, scope)
);
create index if not exists idx_language_bank_count on pulse.language_bank (count);
create index if not exists idx_language_bank_last_seen on pulse.language_bank (last_seen);

create table if not exists pulse.language_bank_mentions (
    mention_id bigint primary key references pulse.mentions (id),
    banked_at timestamp default (now() at time zone 'utc')
);

-- ── Access ───────────────────────────────────────────────────────────────

create table if not exists pulse.users (
    id bigint generated by default as identity primary key,
    email text not null unique,
    display_name text default '',
    role text default 'reviewer',
    password_hash text default '',
    active boolean default true,
    created_at timestamp default (now() at time zone 'utc'),
    last_login_at timestamp                   -- SQLite v4
);

-- sessions.id holds sha256(token), never the token itself.
create table if not exists pulse.sessions (
    id text primary key,
    user_id bigint not null references pulse.users (id),
    created_at timestamp default (now() at time zone 'utc'),
    expires_at timestamp not null,
    last_seen_at timestamp,
    csrf_token text default ''                -- SQLite v4
);
create index if not exists idx_sessions_user on pulse.sessions (user_id);
create index if not exists idx_sessions_expires on pulse.sessions (expires_at);

-- ── Security ─────────────────────────────────────────────────────────────

-- Application role: NOLOGIN, no password. Connect as `postgres`, or create a
-- login role that is a member of pulse_app (README, "Least-privilege login").
do $$
begin
    if not exists (select 1 from pg_roles where rolname = 'pulse_app') then
        create role pulse_app nologin;
    end if;
end
$$;

alter table pulse.schema_version enable row level security;
alter table pulse.settings enable row level security;
alter table pulse.runs enable row level security;
alter table pulse.actions enable row level security;
alter table pulse.usage_log enable row level security;
alter table pulse.usage_events enable row level security;
alter table pulse.sources enable row level security;
alter table pulse.mentions enable row level security;
alter table pulse.triage enable row level security;
alter table pulse.escalations enable row level security;
alter table pulse.drafts enable row level security;
alter table pulse.audit_log enable row level security;
alter table pulse.briefs enable row level security;
alter table pulse.trend_terms enable row level security;
alter table pulse.language_bank enable row level security;
alter table pulse.language_bank_mentions enable row level security;
alter table pulse.users enable row level security;
alter table pulse.sessions enable row level security;

-- Nobody but the owner and pulse_app: strip PUBLIC, and Supabase's API roles
-- when they exist (a plain Postgres, e.g. the test database, has none).
revoke all on schema pulse from public;
revoke all on all tables in schema pulse from public;
revoke all on all sequences in schema pulse from public;
revoke all on function pulse.audit_log_append_only() from public;

do $$
declare
    api_role text;
begin
    foreach api_role in array array['anon', 'authenticated'] loop
        if exists (select 1 from pg_roles where rolname = api_role) then
            execute format('revoke all on schema pulse from %I', api_role);
            execute format('revoke all on all tables in schema pulse from %I', api_role);
            execute format('revoke all on all sequences in schema pulse from %I', api_role);
            execute format('revoke all on all functions in schema pulse from %I', api_role);
            execute format('alter default privileges in schema pulse revoke all on tables from %I', api_role);
            execute format('alter default privileges in schema pulse revoke all on sequences from %I', api_role);
            execute format('alter default privileges in schema pulse revoke all on functions from %I', api_role);
        end if;
    end loop;
end
$$;

grant usage on schema pulse to pulse_app;
grant select, insert, update, delete on all tables in schema pulse to pulse_app;
grant usage, select on all sequences in schema pulse to pulse_app;
-- Append-only, also at the privilege level: the app may only add audit rows.
revoke update, delete, truncate on pulse.audit_log from pulse_app;
-- The schema version is owned by migrations, not the app.
revoke insert, update, delete, truncate on pulse.schema_version from pulse_app;

-- RLS is on and there are no policies for anon/authenticated, so they see
-- nothing even if a grant slips in. pulse_app (not the table owner, so RLS
-- applies to it) gets one allow-all policy per table.
do $$
declare
    tbl text;
begin
    foreach tbl in array array[
        'schema_version', 'settings', 'runs', 'actions', 'usage_log', 'usage_events',
        'sources', 'mentions', 'triage', 'escalations', 'drafts', 'audit_log', 'briefs',
        'trend_terms', 'language_bank', 'language_bank_mentions', 'users', 'sessions'
    ] loop
        execute format('drop policy if exists pulse_app_all on pulse.%I', tbl);
        execute format(
            'create policy pulse_app_all on pulse.%I for all to pulse_app using (true) with check (true)',
            tbl);
    end loop;
end
$$;

-- ── Version ──────────────────────────────────────────────────────────────

insert into pulse.schema_version (version, description)
values (5, '0001_pulse_schema: SQLite migrations v1-v5')
on conflict (version) do nothing;
